### ISSUE TITLE
GPU Support?

### ISSUE THREAD

**Issue by MasonProtter** [JuliaFolds/Transducers.jl#236]
I know this is probably a huge complicated rabbit-hole, but I figured I should at least open an issue to track. Are GPU transducers a thing? Would it be incredibly hard to support GPU parallelism in this package?

**Comment by tkf** [comment]
Simple things worked last time I tried:

> Stateless and non-terminating transducers can be used without Transducers’ custom `foldl` / `reduce` . This means that Transducers.jl now “supports” CuArrays’ `reduce` .
>
> ```julia
> using Transducers, CuArrays, CUDAnative
> A = CuArray(randn(3, 3))
> rf = reducingfunction(Map(CUDAnative.sin) |> Filter(x -> x > 0), +)
> reduce(rf, A, init=0.0f0, dims=1)
> ```
>
> --- https://discourse.julialang.org/t/ann-transducers-jl-0-3-taking-zeros-seriously-type-stability-improvements-fusible-groupby-onlinestats-gpu-support-and-more/26873

It would be interesting to look into how to support stateful transducers but I don't know GPU programming enough to guess how difficult it would be.

**Comment by tkf** [comment]
We now have some simple supports in https://github.com/JuliaFolds/CUDAFolds.jl. Let's track some more future improvements there.
