### ISSUE TITLE
Shift transducer?

### ISSUE THREAD

**Issue by juliohm** [JuliaFolds/Transducers.jl#293]
Is it possible to have a transducer that shifts an iterator by an offset that can be positive or negative? The items pass the end of the iterator would be placed in the beginning cyclically.

**Comment by tkf** [comment]
To cycle an iterator, you can use `Transducers.Inject(Iterators.cycle(itr))`: https://tkf.github.io/Transducers.jl/dev/manual/#Transducers.Inject. Or you can also just `zip` it with the input collection.

For shifting an iterator, I think the easiest approach is to pre-process it with `circshift[!]`.
