### ISSUE TITLE
Don't spawn any tasks in reduce if bassize > length(itr)

### ISSUE THREAD

**Issue by MasonProtter** [JuliaFolds/Transducers.jl#307]
It'd be nice if these could be comparably fast when `basesize > length(itr)`
```julia
julia> @btime foldl(+, Map(identity), [1,2,3,4])
  24.518 ns (1 allocation: 112 bytes)
10

julia> @btime reduce(+, Map(identity), [1,2,3,4], basesize=1000)
  3.339 μs (22 allocations: 1.28 KiB)
10
```
so that users don't need to write their own branching code to avoid spawning unnecessary tasks.

**Comment by tkf** [comment]
Thanks for catching this!

Actually, there should be no spawn in this code path. It looks like most of the overheads are due to dynamic dispatches. Forcing the specialization by the famous "black magic" #309 helps it.

**Comment by tkf** [comment]
> ![image](https://user-images.githubusercontent.com/29282/85350585-5c12b980-b4b6-11ea-98ce-d35c073ce47b.png)
> -- https://github.com/JuliaFolds/Transducers.jl/pull/309#issuecomment-647851179

**Comment by MasonProtter** [comment]
Nice!
