### ISSUE TITLE
Partition ->  ERROR: LoadError: MethodError: no method matching +(::Int64, ::SubArray{Int64,1,Array{Int64,1},Tuple{UnitRange{Int64}},true})

### ISSUE THREAD

**Issue by masterholdy** [JuliaFolds/Transducers.jl#380]

**Comment by tkf** [comment]
`basesize=8` is the correct way to specify number of items per task.

FYI, you can't use `Transducers.Partition` with `reduce`.  But you can use `Iterators.parallel`:

```julia
julia> reduce(+, Iterators.partition(1:20, 8) |> Map(sum))
210
```

There are various reasons why you don't get performance boosts when using threading in Julia.  Note that you have to optimize `LangfordParallel.loop_inner` first.  From a quick look, the inner loop uses something like [`sum([loop_inner(parentValue, value, i, depth, s, n, sn) for i=0:possibilites])`](https://github.com/masterholdy/julia-threading-question/blob/c8e02c340ad4dedda383ed96cf9d8206c1875c6d/langford.jl#L28) and [`zeros(sn)`](https://github.com/masterholdy/julia-threading-question/blob/c8e02c340ad4dedda383ed96cf9d8206c1875c6d/langford.jl#L42) to allocate arrays.    These are not performance-friendly patterns even for single-threaded code.  For example, the `sum` can be written as `sum(loop_inner(parentValue, value, i, depth, s, n, sn) for i=0:possibilites)` or `sum(i -> loop_inner(parentValue, value, i, depth, s, n, sn), 0:possibilites)` to completely avoid allocating an array.

**Comment by masterholdy** [comment]
thank you for your response!

yeah the `zeros(sn)` was commentet out  i already was using 
`    return sum([loop_inner(parentValue, value, i, depth, s, n, sn) for i=0:possibilites]) `
in my sequential code - but was playing around with various variants in my parallel code
https://github.com/masterholdy/julia-threading-question/blob/master/langford.jl#L28


_______

just to clarify, 
what i would want is for the inner loop to be run on all threads if possible
i've got 16 threads and at depth 1 ive got 10 calls to the inner loop (the amount of calls is small at the beginning but its getting called recursive alot)  - i would like these 10 calls to be spread across 10 threads
and if i would be at depth 2 ive got ~5 inner loop calls
so in theory just using some sort of parallel reduce at depth 1 should be an improvement, because the programm for small N's  (here 12) already takes ~1minute and for  and if i go up 1 step to N=15 it already takes hours
so i cant imagine the coast of starting the threads is higher then the gain i would get
but it looks like that currently :D

____

i tried to use `Iterators.partition` as the second parameter i choose `1` so that all threads have something to do
but i couldnt get it to work

```
return Transducers.reduce(+, 0:possibilites |>  Map(idx -> LangfordParallel.loop_inner(parentValue, value, idx, depth, s, n, sn)); basesize=1, init=0)
```
is working, to get `Iterators.partition` to work - i just tried to swap out `0:possibilites` for `Iterators.partition(0:possibilites, 1)`
and remove the extra settings (`; basesize=1, init=0`), and i added a `|> Map(sum)` for the "inner arrays" to be summed before summing the "outter arrays" 
[[a,b,c],[d,e,f]] => [a+b+c, d+e+f] => a+b+c+d+e+f

so i ended up with 
```
return Transducers.reduce(+, Iterators.partition(0:possibilites, 1) |>  Map(idx -> LangfordParallel.loop_inner(parentValue, value, idx, depth, s, n, sn)) |> Map(sum)) 
```

but im getting a 
`ERROR: LoadError: MethodError: no method matching +(::Int64, ::SubArray{Int64,1,UnitRange{Int64},Tuple{UnitRange{Int64}},true})`

just 
```
 Iterators.partition(0:possibilites, 1) |>  Map(idx -> LangfordParallel.loop_inner(parentValue, value, idx, depth, s, n, sn)) |> Map(sum)
```
looks to be working - if i print that i get 
` Base.Iterators.PartitionIterator{UnitRange{Int64}}(0:10, 1) |> Map(Main.LangfordParallel.λ❓) |> Map(sum) `
i dont know if this means that that part atleast is working or not - but i hope so

**Comment by tkf** [comment]
Use `basesize = 1`, if _each_ call to `LangfordParallel.loop_inner` takes a long time (> 100 micro seconds, say).

Also, I recommend you to read the documentation and understand how `Iterators.partition` work.  You are using `Iterators.partition` (and `Partition`) wrongly. If the documentation of `Iterators.partition` is not clear, I encourage you to ask a question in http://discourse.julialang.org (or other Julia community websites https://julialang.org/community/).

**Comment by masterholdy** [comment]
i just tried 
```  
return Iterators.partition(0:possibilites, 1) |> Map(range -> Transducers.reduce(+, range |>  Map(idx -> loop_inner_parallel(parentValue, value, idx, depth, s, n, sn)); basesize=1, init=0)) |> sum  
```

and atleast i get the expected result but  changing the `JULIA_NUM_THREADS` doesnt really impact the run time

```
#JULIA_NUM_THREADS=1 julia main_langford.jl   45698.234399 ms           40513.1056 ms
#JULIA_NUM_THREADS=2 julia main_langford.jl   39077.684999 ms           38924.6652 ms
#JULIA_NUM_THREADS=4 julia main_langford.jl   38940.0916 ms             38998.0866 ms
#JULIA_NUM_THREADS=8 julia main_langford.jl   39327.3791 ms             39026.4072 ms
#JULIA_NUM_THREADS=10 julia main_langford.jl  39076.937601 ms           38916.875401 ms
#JULIA_NUM_THREADS=12 julia main_langford.jl  45711.3647 ms             38403.010498999996 ms
#JULIA_NUM_THREADS=16 julia main_langford.jl  23428.894599 ms           23363.5123 ms
```

i also ran that code for a bigger with 16 threads an and it took `5 hours 55min` while the sequential code ran for `5 hours`
running the same code - for the same problem size - with 8 threads it took `5 hours and 53 min` so 2 min less with half the threads

**Comment by tkf** [comment]
As I said, you don't need partition here.  I also recommend you to read the documentation and understand how the function works before using it.

You are running `reduce` on a vector with single element.  There is nothing to be parallelized for such input.

```julia
julia> possibilites = 3
3

julia> ys = Iterators.partition(0:possibilites, 1) |> Map(range -> @show(range)) |> collect;
range = 0:0
range = 1:1
range = 2:2
range = 3:3

julia> ys
4-element Vector{UnitRange{Int64}}:
 0:0
 1:1
 2:2
 3:3

julia> map(length, ys)
4-element Vector{Int64}:
 1
 1
 1
 1
```

Did you try something like

```julia
ThreadsX.sum(
    idx -> loop_inner_parallel(parentValue, value, idx, depth, s, n, sn),
    0:possibilites;
    basesize = 1,
    init = 0,
)
```

?  Please do note that this requires each call to `loop_inner_parallel` takes sufficiently long time (e.g., > 100 micro seconds).

**Comment by masterholdy** [comment]
yeah i tried 

```
        return ThreadsX.sum(LangfordParallel.loop_inner(parentValue, value, idx, depth, s, n, sn) for idx in 0:possibilites)
```

at some point, with your THreadsX code 
more threads equal to longer calculation times

```
return ThreadsX.sum(
            idx -> loop_inner_parallel(parentValue, value, idx, depth, s, n, sn),
            0:possibilites;
            basesize = 1,
            init = 0,
        )
```

```
JULIA_NUM_THREADS=1 julia main_langford.jl  Elapsed time in microseconds : 26464.994799 ms
JULIA_NUM_THREADS=2 julia main_langford.jl  Elapsed time in microseconds : 28001.232901000003 ms
JULIA_NUM_THREADS=4 julia main_langford.jl  Elapsed time in microseconds : 30982.845999999998 ms
JULIA_NUM_THREADS=8 julia main_langford.jl  Elapsed time in microseconds : 43201.5935 ms
JULIA_NUM_THREADS=10 julia main_langford.jl Elapsed time in microseconds : 50726.9795 ms
JULIA_NUM_THREADS=12 julia main_langford.jl Elapsed time in microseconds : 50374.6389 ms
JULIA_NUM_THREADS=16 julia main_langford.jl Elapsed time in microseconds : 58896.9224 ms
```

> Please do note that this requires each call to loop_inner_parallel takes sufficiently long time (e.g., > 100 micro seconds).
they all do.
