### ISSUE TITLE
Drain / side-effects?

### ISSUE THREAD

**Issue by tbenst** [JuliaFolds/Transducers.jl#436]
Hi, thanks for this great package! I'm exploring using this approach for a real-time application. It took me a moment to realize how to use this with values that are acquired in a streaming fashion, so perhaps this simple example will be helpful to others:

```julia
using Transducers
using Base: iterate

struct IntStream
    length::Int
    sleepTime::Real
end

function Base.iterate(iter::IntStream)
    sleep(iter.sleepTime)
    return (1,2)
end

function length(is::IntStream)
    return is.length
end

function Base.iterate(iter::IntStream, state)
    if state > iter.length
        return nothing
    else
        sleep(iter.sleepTime)
        return (state,state+1)
    end
end

x = IntStream(10,0.1)

function printPass(x)
    println(x)
    x
end

# works, hurray!
IntStream(10,0.1) |> Map(printPass) |> sum

# is there a better way to run code with side-effects than map then collect a bunch of nothing?
IntStream(10,0.1) |> Map(x -> println(x)) |> collect
```

I'm not quite sure what the proper pattern is for side-effects / IO, so figured I'd ask. In [streamly](https://hackage.haskell.org/package/streamly) this would be done by combination of [`drain`](https://hackage.haskell.org/package/streamly-0.7.2/docs/Streamly-Prelude.html#v:drain) to run a stream and discard results, and [`mapM`](https://hackage.haskell.org/package/streamly-0.7.2/docs/Streamly-Prelude.html#v:mapM) to run an effectful computation on a given type.

Also, the above example can be made _much_ more cleanly with `GeneratorsX`, super neat!
```julia
using GeneratorsX
@generator function generateInts(n,sleepTime)
    for i in 1:n
        sleep(sleepTime)
        @yield i
    end
end;

generateInts(10, 0.1) |> Map(printPass) |> sum
```

**Comment by tkf** [comment]
FYI, I usually use `foldxl(right, xs)` for this. If you want a single function, DataTools.jl defines `lastitem(xs) = foldxl(right, Map(identity), xs)`. https://juliafolds.github.io/DataTools.jl/dev/#DataTools.lastitem

I think adding `drain` would be redundant so let me close this issue. But please feel free to expand the discussion/comments here.

PS: It's great to know that you enjoy the package!

**Comment by tbenst** [comment]
Sorry to bump an old thread, but a year later I found this from google and just wanted to complete it for future viewers :)

```julia
@fgenerator function gen_range(n)
    for i in 1:n
        @yield i
    end
end

info(x...) = @info x
drain(func) = foldxl(func ∘ right)

gen_range(5) |> drain(info)
```
Of course, let me know if there's a better way. I do think that `drain(func)` is more intuitive than `foldxl(func ∘ right)`, as eXtended left fold isn't a common functional programming concept.

**Comment by tbenst** [comment]
oops, it turns out this doesn't quite work:
```julia
=== Desired output ===
[ Info: 1
[ Info: 2
[ Info: 3
[ Info: 4
[ Info: 5
[ Info: 6
[ Info: 7
[ Info: 8
[ Info: 9
[ Info: 10

=== Transducers output ===
2
3
4
5
6
7
8
9
10
```

The transducers approach is missing the first number, and also `[ Info: ` is oddly missing..? I use this visual cue for logging. Let me know if any ideas?
