### ISSUE TITLE
Map with progress bar

### ISSUE THREAD

**Issue by JinraeKim** [JuliaFolds/Transducers.jl#468]
I mostly use `Map` for various purposes.
As described in [the documentation](https://juliafolds.github.io/Transducers.jl/stable/reference/manual/#Transducers.withprogress), visulation of progress bar seems to support `foldxl`.

It would be great if such visualisation is also possible when using e.g. `Map`.

**Comment by lassepe** [comment]
This already works:

```julia
using Logging: global_logger # part of base
using TerminalLoggers: TerminalLogger # The logger that displays the progress log https://c42f.github.io/TerminalLoggers.jl/stable/
using Transducers: Map, withprogress

# set TerminalLogger as your global logger:
global_logger(TerminalLogger())

# your transducer pipeline
data = 1:100
data |> withprogress |>  Map() do x;  sleep(0.01); x end|> collect
```

**Comment by JinraeKim** [comment]
> This already works:
> 
> ```julia
> using Logging: global_logger # part of base
> using TerminalLoggers: TerminalLogger # The logger that displays the progress log https://c42f.github.io/TerminalLoggers.jl/stable/
> using Transducers: Map, withprogress
> 
> # set TerminalLogger as your global logger:
> global_logger(TerminalLogger())
> 
> # your transducer pipeline
> data = 1:100
> data |> withprogress |>  Map() do x;  sleep(0.01); x end |> collect
> ```
> 
> Output:
> 
> ```
> foldl 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| Time: 0:00:02
> ```

Thank you @lassepe !
I'm not familiar with loggers, so I wonder if the lines related to logging are mandatory in your example.

**Comment by JinraeKim** [comment]
@lassepe 
If you don't mind, can you explain the mechanism of displaying progress by `global_logger(TerminalLogger())` in your example?

**Comment by lassepe** [comment]
Logging is documented in the [julia docs](https://docs.julialang.org/en/v1/stdlib/Logging/). [This section](https://docs.julialang.org/en/v1/stdlib/Logging/#Loggers) explains in greater detail how custom loggers, such as `TerminalLogger` hook into this machinery.
